# Generated by Django 4.2.15 on 2024-09-03 18:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'invalid': 'Enter a valid email address.'}, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'A subscriber with this email address already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
