# Generated by Django 5.1 on 2024-08-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
