# Generated by Django 5.1 on 2024-08-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
